# NordVPN Credentials Setup Script
# Generates the auth file from environment variables for security

param(
    [string]$CredentialsEnvPath = "config/vpn/providers/nordvpn/credentials.env",
    [string]$AuthFilePath = "vpn/credentials/nordvpn.auth"
)

Write-Host "Setting up NordVPN credentials from environment variables..." -ForegroundColor Green

# Check if credentials.env exists
if (-not (Test-Path $CredentialsEnvPath)) {
    Write-Error "Credentials file not found: $CredentialsEnvPath"
    Write-Host "Please create $CredentialsEnvPath with your NordVPN credentials." -ForegroundColor Yellow
    exit 1
}

# Read environment variables from the credentials.env file
$credentials = @{}
Get-Content $CredentialsEnvPath | Where-Object { $_ -match '^[^#].*=' } | ForEach-Object {
    $key, $value = $_ -split '=', 2
    $credentials[$key.Trim()] = $value.Trim()
}

# Validate required credentials
if (-not $credentials.ContainsKey('VPN_USERNAME') -or -not $credentials.ContainsKey('VPN_TOKEN')) {
    Write-Error "Missing required credentials in $CredentialsEnvPath"
    Write-Host "Please ensure VPN_USERNAME and VPN_TOKEN are set in the credentials file." -ForegroundColor Yellow
    exit 1
}

# Check if credentials are still placeholder values
if ($credentials['VPN_USERNAME'] -eq 'your_nordvpn_email@example.com' -or
    $credentials['VPN_TOKEN'] -eq 'your_nordvpn_access_token') {
    Write-Warning "Credentials appear to be placeholder values."
    Write-Host "Please update $CredentialsEnvPath with your actual NordVPN credentials." -ForegroundColor Yellow
    exit 1
}

# Generate the auth file
$authContent = @"
# NordVPN Token Authentication File
# Generated from environment variables on $(Get-Date)
# DO NOT EDIT THIS FILE DIRECTLY - Edit $CredentialsEnvPath instead

$($credentials['VPN_USERNAME'])
$($credentials['VPN_TOKEN'])
"@

# Create directory if it doesn't exist
$authDir = Split-Path $AuthFilePath -Parent
if (-not (Test-Path $authDir)) {
    New-Item -ItemType Directory -Path $authDir -Force | Out-Null
}

# Write the auth file
$authContent | Out-File -FilePath $AuthFilePath -Encoding ASCII -Force

Write-Host "NordVPN credentials file generated successfully: $AuthFilePath" -ForegroundColor Green
Write-Host "Credentials loaded for user: $($credentials['VPN_USERNAME'])" -ForegroundColor Cyan

